### ISSUE TITLE
Card IO: Focus Timing while taking screenshots

### ISSUE THREAD

**Issue by biksappdev** [card-io/card.io-iOS-SDK#100]
Hi Team,
I have a question regarding the image capture timing using Card IO for iOS apps. Whenever I try to scan a card, it captures a picture instantly without focusing on it and hence leads to a blurry capture. Is there a way to auto-focus on the card and capture only when there is a clear focussed image?

Any help is appreciated. 
Thanks,
Bikram.

**Comment by dgoldman-ebay** [comment]
@biksappdev interesting. The code does set the camera to autofocus, and the code trigger an autofocus whenever it's not happy with the images it's receiving.

In your case, are you asking simply for an image capture, without scanning? I.e., are you setting `CardIODetectionModeCardImageOnly` to `YES`? If so, notice this comment from `CardIOPaymentViewController.h`:
```
/// @note Images returned in CardIODetectionModeCardImageOnly mode may be less focused, to accomodate scanning
///       cards that are dominantly white (e.g., the backs of drivers licenses), and thus
///       hard to calculate accurate focus scores for.
```

**Comment by biksappdev** [comment]
@dgoldman-ebay , I am using both but the scenario happens while scanning payment cards too for which I have as below : 
self.cardIOViewController.detectionMode = CardIODetectionModeCardImageAndNumber;
The moment I try to capture a Credit/Debit card, it captures picture instantly without focusing. 
Also, I have another question, my app currently is on version 4.0.0. Are there any improvements/benefits of shifting the latest version currently without impacting on functionality or performance ?
Appreciate the quick response.
Thanks.

**Comment by dgoldman-ebay** [comment]
> The moment I try to capture a Credit/Debit card, it captures picture instantly without focusing. Am I missing anything else ? 

I don't think that you're missing anything.

If the code is able to successfully scan the card number, then by our definition the focus is acceptable.

One thing to note is that we are using a camera resolution of only 640x480. So you can't expect a super-sharp image in any case.


> Also, I have another question, my app currently is on version 4.0.0. Are there any improvements/benefits of shifting the latest version currently without impacting on functionality or performance ?

You should review the release notes [here](https://github.com/card-io/card.io-iOS-SDK/releases). The biggest update is that card.io can now (for many cards) automatically scan the expiry date as well as the card number.

**Comment by biksappdev** [comment]
![img_0453](https://cloud.githubusercontent.com/assets/9661978/6860125/e8855df8-d3e0-11e4-8440-465fc5f399ef.PNG)
![img_0454](https://cloud.githubusercontent.com/assets/9661978/6860124/e88502b8-d3e0-11e4-9ee8-f1f27b24352f.PNG)

@dgoldman-ebay , above are the images I got by capturing non-payment card. If you notice, the images are blurry and it was captured instantly without any focus. Any help would be appreciated to resolve this.

**Comment by dgoldman-ebay** [comment]
@biksappdev I certainly see what you mean. But I think the `Images returned in CardIODetectionModeCardImageOnly mode may be less focused` comment applies here.

It might be possible to find a spot in our code where we could explicitly force an initial camera focus (if we're not already doing so). If you're interested in taking a look at our [open-sourced code](https://github.com/card-io/card.io-iOS-source) yourself, I'd be happy to try to point you toward the relevant sections.

Otherwise, our own limited resources are focused mainly on payment cards right now, so I don't think I'll be able to jump in myself to improve this for you.

**Comment by biksappdev** [comment]
@dgoldman-ebay , sure thing. I would like to resolve this and any help is greatly appreciated. Could you please provide me pointers for it ?

**Comment by dgoldman-ebay** [comment]
@biksappdev I did end up taking a quick look, and on all of my tests the camera's autofocus got triggered at least once before the scan returned. None of my test cards, though, had as little in the way of fine details as did yours.

You'll want to look in the file `CardIOVideoStream.mm`. The method to call in order to trigger an autofocus is `autofocusOnce`. Currently that method gets called no more frequently than every 2 seconds (`kMinTimeIntervalForAutoFocusOnce`), and only if our own measurement of focus indicates a need (`frame.focusSucks`).

Maybe you can find a way to always trigger a single `autofocusOnce` call when the video stream starts up. Hmm. Might be as simple as calling `autofocusOnce` at the end of the `startSession` method.

In any case, let's continue this discussion over in the [card.io-iOS-source repo](https://github.com/card-io/card.io-iOS-source). You can create a new issue or a Pull Request in that repo when you're ready.

P.S. After this comment, I probably won't be available for quick responses until Monday. Good luck!

**Comment by biksappdev** [comment]
Hi @dgoldman-ebay , thanks for the response. Currently I think I am on a time crunch to resolve this and release to pacify complaining customers because of this issue. Is there a quick way I can set this up in my app before capturing an image using CardIO. Can I default to a particular focus mode for all card scanning ? Any help is much appreciated.

**Comment by dgoldman-ebay** [comment]
Sorry, @biksappdev, but I can't think of any quick fix for you.

@josharian, any ideas?

**Comment by josharian** [comment]
IIRC, iOS 8 gives you the option to set the focal distance of the camera. (I might well recall incorrectly, though.) If so, you could hack in the fixed focal distance that you need. You could also try Dave's suggestion to autofocus once. You could also fiddle with the minimum focus score in the dmz. For any of these, you'd need to go hacking around in the source, since I don't think we'll want to include them in the main repo. And I suspect that you'll have a hard time getting something that you're happy with under time crunch. It'll take some experimentation. Sorry, that's all I've got for the moment.

**Comment by biksappdev** [comment]
@dgoldman-ebay , @josharian , thanks a lot for the replies. So in case I make the change to call [self autofocusOnce] after starting the session, whats the way to test this in my app ? Do I just build the app and create a new .a lib version and replace it within my app ? I am trying to understand the dependencies here in case I have to test the changes.

**Comment by biksappdev** [comment]
Also, If I call this code before I launch the CardIOViewController to scan images, would it give me any leverage or does CardIO over-ride this code ?

- (void)setCameraFocusMode {
    Class captureDeviceClass = NSClassFromString(@"AVCaptureDevice");
    
    if (captureDeviceClass != nil) {
        AVCaptureDevice *cameraDevice = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
        AVCaptureSession *session = [[AVCaptureSession alloc] init];
        [session beginConfiguration];
        
        if ([cameraDevice respondsToSelector:@selector(isAutoFocusRangeRestrictionSupported)] && cameraDevice.autoFocusRangeRestrictionSupported) {
            // If we are on an iOS version that supports AutoFocusRangeRestriction and the device supports it
            // Set the focus range to "near"
            if ([cameraDevice lockForConfiguration:nil]) {
                cameraDevice.autoFocusRangeRestriction = AVCaptureAutoFocusRangeRestrictionNear;
                cameraDevice.focusMode = AVCaptureFocusModeContinuousAutoFocus;
                [cameraDevice unlockForConfiguration];
            }
        }
        [session commitConfiguration];
    }
}

**Comment by dgoldman-ebay** [comment]
> So in case I make the change to call [self autofocusOnce] after starting the session, whats the way to test this in my app ? Do I just build the app and create a new .a lib version and replace it within my app ?

Yes, exactly.

> Also, If I call this code before I launch the CardIOViewController to scan images, would it give me any leverage or does CardIO over-ride this code ?

card.io does override that, but I don't know whether configuring the camera a bit earlier might possibly get it correctly focused sooner. In other words, give it a try!

But you'll probably want to set the focus mode to `AVCaptureFocusModeAutoFocus` to force an immediate autofocus (rather than `AVCaptureFocusModeContinuousAutoFocus`)

**Comment by dgoldman-ebay** [comment]
@biksappdev feel free to re-open this issue if you have more questions.

**Comment by biksappdev** [comment]
@dgoldman-ebay , I am still running into user-experience issues with Card IO, with numerous complaints being immediate card scanning, not giving the user enough time to focus properly on the card and thus results in a blurry image. 
Do you ever run into such issues yourself ?
Could you please share with me a sample POC app which has the latest CardIO integrated ?
Any help is appreciated.

**Comment by dgoldman-ebay** [comment]
@biksappdev I'm sorry to hear that it's not working better for you.

The primary intent for card.io is to scan credit cards, returning the credit card number.

As a convenience to a few specific developers who use card.io, we also added the ability to merely detect the edges of a card and immediately return a card image.

Since this isn't a primary intent, we have not devoted a lot of time to tuning this task. Unfortunately we don't have the resources to do so now.

So I'm afraid that all I can suggest is that you look into our [card.io-iOS-source repo](https://github.com/card-io/card.io-iOS-source) and see what you can do to improve the results when a card image is returned without scanning. We'll continue to be happy to answer questions about the code, but we don't have anyone at the moment who can do the necessary code modifications and experiments.

**Comment by biksappdev** [comment]
Sure thing @dgoldman-ebay , could you please help me integrating sample app with the framework so I can debug and explore to make changes ?

**Comment by biksappdev** [comment]
SO I tried to link the project from source repp with my sample project to debug the code flow and I get the below error at the line below -
#import "warp.h"
'warp.h' file not found.

**Comment by dgoldman-ebay** [comment]
@biksappdev I think you should start with the test app that is already part of the repo, rather than your own app.

Open `icc.xcodeproj` in Xcode and build the target `icc`.

To make changes to which parameters icc sends into the card.io library (e.g., to change `detectionMode` to `CardIODetectionModeCardImageOnly`), see `RootViewController.m`. The `scan` method in that file sets the parameters.

**Comment by biksappdev** [comment]
![screen shot 2015-04-16 at 4 28 44 pm](https://cloud.githubusercontent.com/assets/9661978/7193447/c29d283e-e455-11e4-8d09-7e3627ef0f5a.png)
@dgoldman-ebay , this is the error I get when I do it.

**Comment by dgoldman-ebay** [comment]
@biksappdev when you cloned the repo, did you also clone the `card.io-dmz` submodule?

**Comment by biksappdev** [comment]
@dgoldman-ebay, yes I did..attached is the folder structure where I cloned both the repo. Kindly advise.
![screen shot 2015-04-16 at 4 54 50 pm](https://cloud.githubusercontent.com/assets/9661978/7193706/717acd40-e459-11e4-9df5-fdf5f8f62c2a.png)

**Comment by biksappdev** [comment]
@dgoldman-ebay , I got the above error resolved, thanks !

**Comment by dgoldman-ebay** [comment]
@biksappdev When you clone the `card.io-source` repo, if you properly initialize its submodule you'll find a `dmz` folder within your `cardio-source` folder. That's where the `card.io-dmz` repo should be cloned. (So that the path to `dmz.h` will then be `.... / card.io-source / dmz / dmz.h`.)

**Comment by biksappdev** [comment]
@dgoldman-ebay , I got the app running on device, will explore the code and will let you know if I have any further questions. Thanks for your help.

**Comment by dgoldman-ebay** [comment]
@biksappdev that's great!

For further discussions, could you open a new issue on the card.io-source repo? That way future developers will be able to find and benefit as well.

**Comment by biksappdev** [comment]
sure thing, will do.
