### ISSUE TITLE
SDK couldn't be found in cocoapods when using use_frameworks!

### ISSUE THREAD

**Issue by m1entus** [card-io/card.io-iOS-SDK#115]
When i was trying to include card.io SDK using cocoapods with use_framework! option which is available since cocoapods 3.6 then card.io couldn't be found in project.

**Comment by williamnoto** [comment]
I think I have a similar issue. I don't see a TARGET for Pods-CardIO...

![screen shot 2015-05-27 at 7 38 29 am](https://cloud.githubusercontent.com/assets/6032433/7835008/7d91ea0a-0443-11e5-9e77-82597b5adb3e.png)

and subsequently am getting this link error:

    ld: library not found for -lPods-CardIO
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dgoldman-ebay** [comment]
At the moment, card.io-iOS-SDK is still distributed as a static library rather than a framework, to provide continued compatibility for users running iOS 6 or 7.

Therefore the `use_framework!` option is not compatible with integrating card.io via CocoaPods.

If you really do need `use_framework!` for your project, then you can instead integrate card.io manually, as described [here](https://github.com/card-io/card.io-iOS-SDK#setup). It's still a very easy integration! :smiley_cat: 

Please let us know if you feel there is a better solution we could offer, while continuing to provide backward compatibility for users who are not yet running iOS 8.

**Comment by m1entus** [comment]
You could build framework, even using static library and then make subspec and specify deployment target, examples:
https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec
https://gist.github.com/AL333Z/9895111

**Comment by keith** [comment]
With iOS 9 approaching quickly, and Swift pods becoming more prevalent. It would be really useful for CardIO to support frameworks usage, even if it's directly from the source. We are using `use_frameworks!` and really aren't interested in including this library manually (as none of our other dependencies have this requirement).

**Comment by danielgalasko** [comment]
Such a pity that this issue is closed, the headache involved in using a spec that has CardIO as a dependency means that I can't use frameworks at all:( alternative is to use #126 and have a fork of CardIO that uses vendored libraries

**Comment by josharian** [comment]
This issue may be closed, but the pull request is open. We will review it as soon as we can; the contributors to card.io who understand the CocoaPods integration are swamped at their jobs right now.

**Comment by keith** [comment]
After a little more digging here, we've discovered that CocoaPods will make the necessary project file adjustments to create a module that is importable via Swift without a bridging header *if* there is any `*.m` file in the `source_files` of this pod.

**Comment by keith** [comment]
I've submitted a simple PR that accomplishes this https://github.com/card-io/card.io-iOS-SDK/pull/210

I will probably delete this fork regardless of whether or not the PR is merged so please do not depend on it in your projects.

**Comment by Blahartinger** [comment]
I see this has been merged, are you planning on releasing a new version soon with this in it?
