### ISSUE TITLE
card.io or PayPal logo

### ISSUE THREAD

**Issue by palanishankar** [card-io/card.io-iOS-SDK#134]
i am integrating card.io into my client project and he doesn't want to show neither card.io nor PayPal.
do we have any legal concerns?

-Sam

**Comment by josharian** [comment]
I am not a lawyer, and I can't answer any legal questions.

card.io is open source under a liberal license, so modifying the library and using it is generally permitted.

All that said, we (the authors of card.io) have historically asked that you show one of the two logos out of respect for the fact that it has been provided free and open source. (If your client would prefer, we could probably arrange for a Braintree logo instead of PayPal or card.io.)
