### ISSUE TITLE
card.io not scanning non-16-digit cards

### ISSUE THREAD

**Issue by filamoon** [card-io/card.io-iOS-SDK#161]
It works well for 16-digit visa/mastercard cards, but it does not scan some other cards like ICBC (Industrial and Commercial Bank of China) cards. The number is like: 123456 0123456789012. The numbers are raised indeed.

Is it possible to add more card types programmatically?

Thanks.

**Comment by dgoldman-ebay** [comment]
@filamoon unfortunately, adding support for additional card types (beyond the five currently supported) would involve a *lot* of work. But the card.io team is currently without the resources to take on such a job.

Since card.io is now an open-source project, you're welcome to jump in on what you need. And/or recruit others to do so. See https://github.com/card-io/card.io-iOS-source if you're interested in pursuing that option.
