### ISSUE TITLE
CocoaPod Framework

### ISSUE THREAD

**Issue by bencallis** [card-io/card.io-iOS-SDK#168]
Are there any plans to make CardIO work as a framework when using CocoaPods? We are currently developing a component (which is also a pod) which we hope to use CardIO in. Our component has multiple UI elements which use IB_Designable (which only works correctly with frameworks).

Are there any plans to make CardIO produce a framework with CocoaPods? I noticed you have Carthage support and that only works with frameworks so it seems like it should be possible?

**Comment by bluk** [comment]
There's no immediate plans, but if you or anyone else can issue a PR to https://github.com/card-io/card.io-iOS-source then it would definitely move things forward.

**Comment by danielgalasko** [comment]
+1 would love to tackle this but the source is seriously complicated:(

**Comment by bencallis** [comment]
@danielgalasko yeah due to the dependencies on the image framework I don't think it is a 2 minute job.

**Comment by Duffycola** [comment]
I am trying to use cardIO with CocoaPods and Swift, but it just doesn't find the library. I suppose this is related.. Would be great if the documentation would mention that this isn't supported yet.

What's the problem with the image framework? I have developed the OpenCV iOS port during Google Summer of Code 2012. Maybe I can be of help?

As far as I remember OpenCV is build as a static library using a python script that gathers the source and then issues the appropriate build commands. Do you have some documentation at hand on how to compile a dynamic framework? For more information on the OpenCV side have a look here: http://docs.opencv.org/2.4/doc/tutorials/introduction/ios_install/ios_install.html

**Comment by bencallis** [comment]
@Duffycola I think the issue is CardIO is using a static lib version of OpenCV and you can't (as far as I know) including a static lib in a framework. So to build a Framework of CardIO OpenCV will need be built from source.

**Comment by mjholgate** [comment]
And I think OpenCV uses cmake as a build system?

**Comment by Duffycola** [comment]
OpenCV uses Cmake. For iOS it is a little bit more complicated. A python script (opencv/platforms/ios/build_framework.py) sets up iOS-specific flags, compiles the library, and ultimately creates the mac-typical static framework structure.

Now dynamic frameworks are new to me and it would be good to find documentation about how to invoke xcode to not build a static, but a dynamic framework (from the commandline). Maybe someone more familiar with cocoapods has some knowledge?

Have you experimented with https://cocoapods.org/pods/OpenCV ?
I think in the future it would be best if the cardIO Podspec would list opencv as a dependency rather than shipping a potentially large static library.

I have also raised the issue here: https://github.com/Itseez/opencv/issues/6186

**Comment by bencallis** [comment]
@Duffycola did you get any further with this?

**Comment by ghost** [comment]
Any updates in this topic? I need to include Card.IO in own static framework, so any new idea would be helpful...

**Comment by luisvillara** [comment]
Any updates?

**Comment by dollykosmos** [comment]
Any update?

**Comment by burnto** [comment]
This project and its source counterpart are no longer actively maintained, so we do not expect further updates on this topic. Thanks.

**Comment by dollykosmos** [comment]
Hello Brent,

So any new repository for CARD IO in Swift? If yes, then please specify
