### ISSUE TITLE
Support for credit cards with 8 digits

### ISSUE THREAD

**Issue by danieltskv** [card-io/card.io-iOS-SDK#91]
Is there going to be support for credit cards with 8 digits?
Right now I can't proceed with manual input of 8 digits.

Thank you!

**Comment by dgoldman-ebay** [comment]
@danieltskv card.io is currently designed to scan MasterCard, Visa, American Express, Discovery, and JCB credit cards.

What kind of card are you interested in accepting?

**Comment by danieltskv** [comment]
@dgoldman-ebay In Israel we have a company called Isracard that issues various cards from Mastercard, Visa and more.
The domestic cards, the ones that are only valid in Israel, have 8 letter.
For example:
![download](https://cloud.githubusercontent.com/assets/8099541/5727709/b6aaaae6-9b6d-11e4-9ab4-7a6162c54127.jpg)

We have a lot of them here, and I guess more countries have these domestic cards.
Even if the scan can't read them It will be great if one can input them manually. Right now the user can't proceed with 8 digits.

**Comment by dgoldman-ebay** [comment]
@danieltskv thanks for that information.

For the moment, I guess you have two options: (1) create your own manual-input screen rather than using the card.io screen, or (2) build your own version of card.io based on our [open-source codebase](https://github.com/card-io/card.io-iOS-source) in which you change the behavior of the manual-input screen.

I think that creating your own manual-input screen would be the way to go. Most of the non-obvious code in ours involves credit card number prefixes and the Luhn checksum, which aren't things you'll need to worry about. Creating a screen to simply collect an unchecked card number plus an expiry month/year and perhaps a postal code should be easy for you. (Plus you'll be able to take the user directly to the manual-input screen, with camera scanning a secondary option.)

**Comment by danieltskv** [comment]
@dgoldman-ebay Thank you for the explanation. I will see what is the best option for us.
