### ISSUE TITLE
card.io: appToken must be set prior to presenting the CardIOView.

### ISSUE THREAD

**Issue by invmobiledev** [card-io/card.io-iOS-SDK#95]
Hi!

I have been thru the other issue that reported a similar behavior. But since that was with respect to the PayPal SDK, i have reported this as a new issue.

I downloaded the most recent release (v5.0.1) of the SDK and worked my way to integrate the functionality to present as a view controller in my application. The behavior is as follows - 

- ScanViewController presentation code is executed.
- Before the view controller is presented, userDidCancelPaymentViewController method is called and i see the message on the console - "card.io: appToken must be set prior to presenting the CardIOView."
- The ScanViewController is now presented.
- any interaction with the presented view controller after this point results in an application crash.

I analyzed the header files and the options available and observe that appToken variable is not declared.

Requesting help on this.

**Comment by dgoldman-ebay** [comment]
@invmobiledev :

1. The PayPal iOS SDK contains its own copy of the card.io SDK. So if your project includes the PayPal iOS SDK, then you must not also add the card.io SDK to your project.

2. The error message regarding `appToken` implies that you have an old version of the card.io SDK somewhere in your project. `appToken` was removed in card.io 3.10.0.

3. I wonder whether your problem comes from including an old version of the PayPal iOS SDK in your project. You should update to the latest version of the [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK).

**Comment by invmobiledev** [comment]
@dgoldman-ebay As per your comment, i analyzed my project to check for older version of Card.IO.

Turns out, an older version was present in the resources(MiSnap SDK) which was causing this conflict. 

Removing this made it work like a charm. Expiry Scanning works neatly.

Thank You!

**Comment by dgoldman-ebay** [comment]
Sounds great, @invmobiledev!
